#!/bin/bash

#
# SendPatch: Copy updated source file to a particular tenant
#
# Usage is: 
#
#         SendPatch <tenant-id> <file>
#
# Where <tenant-id> is the five-digit tenant ID 
#       <file> is something in the /shared/latest director tree
#

DIR=/opt/TTutils             # Install Directory
ROOT=/shared/latest          # root of file depot
PEM=$DIR/conf/Appliance.pem  # Private key to login
CACHE=$DIR/data/Status.cache
MAXAGE=900
SSHOPT="-o UserKnownHostsFile=/dev/null"

if [ -z "$1" ]; then 
   echo "ERROR: No tenant ID"
   exit 8
fi

if [ -z "$2" ]; then
   echo "ERROR: No file"
   exit 8
fi

if [ ! -f "$ROOT/$2" ]; then 
   echo "ERROR file $2 not found in $ROOT"
   exit 8 
fi

if [ "$EUID" != "0" ]; then
   echo "Not running with root privileges"
   exit 8
fi

echo "Connecting to tenant $1"

# The Status script can be slow, so we have a cached version

AGE=$(echo $(( `date +%s` - `stat -L --format %Y $CACHE` )))
if [ "$AGE" -lt "$MAXAGE" ]; then
   echo "Using cached status"
   IP=`cat $CACHE  | grep "Tenant:$1" | cut -f 2 -d ":" | cut -f 1` 
   if [ -z "$IP" ]; then
      IP=`$DIR/Status | grep "Tenant:$1" | cut -f 2 -d ":" | cut -f 1` 
   fi
else
   IP=`$DIR/Status | grep "Tenant:$1" | cut -f 2 -d ":" | cut -f 1` 
fi

if [ -z "$IP" ]; then
   echo "ERROR: Tenant $1 not found"
   exit 4
fi

echo "Using SCP to Tenant $1 on IP $IP to copy /shared/$2 -> /appliance/$2"
scp -i $PEM -P 11022 $SSHOPT /shared/latest/$2 master@$IP:/appliance/$2

exit $?

