#!/bin/sh
### BEGIN INIT INFO
# Provides:          rcshutdown
# Required-Start:    
# Required-Stop:     $network
# Should-Stop:   
# X-Start-Before    
# X-Stop-After:	     openvpn  
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Executes the /etc/rc.shutdown script at shutdown
# Description:       Executes the /etc/rc.shutdown script at shutdown
#                    if such a script exists.
### END INIT INFO


LOCKFILE=/var/lock/subsys/rcshutdown
logger "RCSHUTDOWN Service with $@"
echo   "RCSHUTDOWN Service with $@" >&2

. /lib/lsb/init-functions

case "$1" in
  start)
        logger "$0 $LOCKFILE created"
        touch $LOCKFILE
	echo "$0 started" >&2
        exit 0 
	;;
  stop)
        if [ -f "$LOCKFILE" ];then 
           rm $LOCKFILE
        fi
        if [ -f "/etc/rc.shutdown" ]; then
           logger "$0 running /etc/rc.shutdown"
           /etc/rc.shutdown 
        else
           logger "$0 - no /etc/rc.shutdown found"
        fi
        ;;
  restart|reload|force-reload)
	echo "Error: '$1' not supported" >&2
	exit 3
	;;
  *)
	echo "Usage: rcshutdown [start|stop]" >&2
	exit 3
	;;
esac
